# Copyright 2021 Yahoo, Licensed under the terms of the Apache License, Version 2.0.
# See LICENSE file in project root for terms.

DATASET:
  AUGMENTATION:
    IMAGE_AUGMENTATION: null
  CLASS_WEIGHTS: null
  IMAGE_DIR: null
  NAME: imat_fashion
  NUM_CLASSES: null
  PATH: /home/default/ephemeral_drive/Data/imat2018/
  REQUIRE_IMAGES: false
  SINGLE_CLASS_BATCHES: false
DATA_LOADER:
  LOADER_NUM_WORKERS: 0
EXP_NAME: clipresmaaf-imat-lrm5-pt0_1-adam
MODEL:
  CLIP:
    MISALIGNMENT: null
    PROMPT: ''
  COMPOSITION: clipresmaaf
  DEVICE: cuda
  DROPOUT_RATE: 0.1
  EMBED_DIM: 1024
  IMAGE_MODEL:
    ARCHITECTURE: null
    FREEZE_WEIGHTS: false
    OUTPUTS:
    - 4
    - attnpool
    PRETRAINED: true
    WEIGHTS: null
  INCLUDES_IMAGE_TRANSFORM: false
  INITIAL_NORMALIZATION_FACTOR: 4.0
  LOSS: batch_based_classification  # consider double_softmax
  MAAF:
    ATTENTION_HEADS: 8
    ATTN_SOFTMAX_REPLACEMENT: null
    BLOCK_WIDTH: 256
    NUM_BLOCKS: 1
    OUTPUT: rwpool
    POSITION_ENCODING: null
    RESIDUAL:
      INITIAL_MAAF_PRESIGMOID: -5.0
      LEARN_WEIGHTS: true
  TEXT_MODEL:
    ARCHITECTURE: null
    EMBED_DIM: 512
    FREEZE_WEIGHTS: false
    MAX_TOKENS: 128
    MAX_VOCAB: 52000
    MODEL_PATH: null
    NUM_LAYERS: 1
    OUTPUT_RELU: false
    TOKENIZER: null
    TOKENIZER_PATH: null
    VOCAB_DATA: null
    VOCAB_MIN_FREQ: 0
OUTPUT_DIR: /home/default/ephemeral_drive/experiments/paper/
SOLVER:
  ALWAYS_EVAL_TEST: false
  BATCH_NORM_MODE: freeze_bn
  BATCH_SIZE: 128
  DROP_WORST_RATE: 0
  EVAL_EVERY: 1
  FINAL_EVAL_ON_TEST: false
  LEARNING_RATE: 1.0e-05
  LEARNING_RATE_DECAY: 0.1
  LEARNING_RATE_DECAY_FREQUENCY: 7254
  LR_DECAY_ONLY_ONCE: false
  MOMENTUM: 0.9
  NUM_ITERS: 21762
  OPTIMIZER: adam
  PRETRAINED_WEIGHT_LR_FACTOR_IMAGE: 0.1
  PRETRAINED_WEIGHT_LR_FACTOR_TEXT: 0.1
  PROJECTION_LR_TIED_TO_PRETRAINED: false
  SAVE_EVERY: 100
  SCHEDULE_ITERS: []
  SCHEDULE_RATES: []
  SOFTMAX_MARGIN: 0
  WEIGHT_DECAY: 1.0e-06
