# Copyright 2021 Yahoo, Licensed under the terms of the Apache License, Version 2.0.
# See LICENSE file in project root for terms.

DATASET:
  AUGMENTATION:
    IMAGE_AUGMENTATION: null
  CLASS_WEIGHTS: null
  IMAGE_DIR: null
  NAME: imat_fashion
  NUM_CLASSES: null
  PATH: /home/default/ephemeral_drive/Data/imat2018/
  REQUIRE_IMAGES: false
  SINGLE_CLASS_BATCHES: false
DATA_LOADER:
  LOADER_NUM_WORKERS: 0
EXP_NAME: clip-imat
MODEL:
  EMBED_DIM: 1024
  COMPOSITION: clip
  DEVICE: cuda
  LOSS: double_softmax
  TEXT_MODEL:
    ARCHITECTURE: null
    TOKENIZER: null
  IMAGE_MODEL:
    ARCHITECTURE: null  # because included in clip
  INCLUDES_IMAGE_TRANSFORM: false
  INITIAL_NORMALIZATION_FACTOR: 4.
OUTPUT_DIR: /home/default/ephemeral_drive/experiments/paper/
SOLVER:
  ALWAYS_EVAL_TEST: false
  BATCH_NORM_MODE: freeze_bn
  BATCH_SIZE: 128
  DROP_WORST_RATE: 0
  EVAL_EVERY: 1
  FINAL_EVAL_ON_TEST: false
  LEARNING_RATE: 1.0e-05
  LEARNING_RATE_DECAY: 0.1
  LEARNING_RATE_DECAY_FREQUENCY: 7254
  LR_DECAY_ONLY_ONCE: false
  MOMENTUM: 0.9
  NUM_ITERS: 21762
  OPTIMIZER: adam
  PRETRAINED_WEIGHT_LR_FACTOR_IMAGE: 1.
  PRETRAINED_WEIGHT_LR_FACTOR_TEXT: 1.
  PROJECTION_LR_TIED_TO_PRETRAINED: true
  SAVE_EVERY: 100
  SCHEDULE_ITERS: []
  SCHEDULE_RATES: []
  SOFTMAX_MARGIN: 0
  WEIGHT_DECAY: 1.0e-06
