# Copyright 2021 Yahoo, Licensed under the terms of the Apache License, Version 2.0.
# See LICENSE file in project root for terms.

DATASET:
  NAME: fashioniq
  PATH: /home/default/ephemeral_drive/Data/FashionIQ/
  REQUIRE_IMAGES: false
  AUGMENTATION:
    IMAGE_AUGMENTATION: false
DATA_LOADER:
  LOADER_NUM_WORKERS: 0
OUTPUT_DIR: /home/default/ephemeral_drive/experiments/
EXP_NAME: random
MODEL:
  EMBED_DIM: 1024
  COMPOSITION: random
  DEVICE: cpu
  LOSS: batch_based_classification
  TEXT_MODEL:
    ARCHITECTURE: null
    TOKENIZER: null
  IMAGE_MODEL:
    ARCHITECTURE: null
  INCLUDES_IMAGE_TRANSFORM: false
